spring:
  main:
    web-application-type: reactive
  application:
    name: banking_gateway
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: http://localhost:9090
          predicates:
            - Path=/account/**
        - id: fundtransfert_route
          uri: http://localhost:9091
          predicates:
            - Header=Service, Fund-Transfer
        - id: report_account_route
          uri: http://localhost:9092
          predicates:
            - Header=Service, Report-Account